import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "react core",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar />
        </div>
        <div className="min-h-screen">{children}</div>
        <footer className="text-center py-5 bg-slate-600 text-white">
          This is footer
        </footer>
      </body>
    </html>
  );
}
